apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: petstagram-cluster
  region: ap-northeast-2
  version: "1.29"

nodeGroups:
  - name: ng-petstagram
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: "petstagram-node-key"
