name: FastAPI ECR Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build & Push FastAPI to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::348823728620:role/GitHubActionsECRPushRole
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: petstagram_be
          file: petstagram_be/Dockerfile
          push: true
          tags: 348823728620.dkr.ecr.ap-northeast-2.amazonaws.com/petstagram-fastapi:latest
